feat(issue-#1): add UI and some support tools
coma8765/literate-computing-machine pull request #2
Opened 2024-06-19 20:16 UTC by coma8765

2024-06-20 13:43 UTC, glebosotov commented on lib/src/presentation/pages/home_page.dart
> +const _kPageTitle = 'Мои дела';
почему все константы снаружи класса

2024-06-20 13:45 UTC, glebosotov commented on lib/src/presentation/pages/home_page.dart
> +      final assetPath = [
такие чудеса если и делать (зачем), то вне билд метода, в отдельном методе

2024-06-20 13:45 UTC, glebosotov commented on lib/src/presentation/pages/home_page.dart
> +    final brightness = MediaQuery.of(context).platformBrightness;
нежелательно завязываться на brightness

2024-06-20 13:45 UTC, glebosotov commented on lib/src/presentation/pages/home_page.dart
> +    final completeColor = AppColors.label.tertiary.resolveFrom(context);
resolve цветов – круто 👍🏻

2024-06-20 13:46 UTC, glebosotov commented on lib/src/presentation/pages/home_page.dart
> +import 'package:flutter/cupertino.dart';
в этом файле много методов, а могли бы быть приватные виджеты. это помогает при дебаге и важно для перформанса

2024-06-20 13:47 UTC, glebosotov commented on lib/src/presentation/pages/utils_page.dart
> +import 'package:flutter/cupertino.dart';
хорошая идея

2024-06-20 13:49 UTC, glebosotov commented on lib/src/presentation/widgets/list_tiles/list_tile.dart
> +                  child: subtitle!,
следует избегать `!` где возможно, можно заменить на `?? const SizedBox.shrink()`

2024-06-20 13:50 UTC, glebosotov commented on lib/src/presentation/widgets/list_tiles/rounded_checkbox.dart
> +        onChanged: (value) {},
полагаю, здесь WIP?
значения никуда не передаются

2024-06-22 23:08 UTC, coma8765 commented on lib/src/presentation/pages/home_page.dart
> +const _kPageTitle = 'Мои дела';
Руководствовался ./flutter/packages/flutter/lib/src/cupertino/list_tile.dart

Это начало файла
```dart
// These constants were eyeballed from iOS 14.4 Settings app for base, Notes for
// notched without leading, and Reminders app for notched with leading.
const double _kLeadingSize = 28.0;
const double _kNotchedLeadingSize = 30.0;
const double _kMinHeight = _kLeadingSize + 2 * 8.0;
const double _kMinHeightWithSubtitle = _kLeadingSize + 2 * 10.0;
const double _kNotchedMinHeight = _kNotchedLeadingSize + 2 * 12.0;
const double _kNotchedMinHeightWithoutLeading = _kNotchedLeadingSize + 2 * 10.0;
const EdgeInsetsDirectional _kPadding = EdgeInsetsDirectional.only(start: 20.0, end: 14.0);
const EdgeInsetsDirectional _kPaddingWithSubtitle = EdgeInsetsDirectional.only(start: 20.0, end: 14.0);
const EdgeInsets _kNotchedPadding = EdgeInsets.symmetric(horizontal: 14.0);
const EdgeInsetsDirectional _kNotchedPaddingWithoutLeading = EdgeInsetsDirectional.fromSTEB(28.0, 10.0, 14.0, 10.0);
const double _kLeadingToTitle = 16.0;
const double _kNotchedLeadingToTitle = 12.0;
const double _kNotchedTitleToSubtitle = 3.0; // 3.0
const double _kAdditionalInfoToTrailing = 6.0;
const double _kNotchedTitleWithSubtitleFontSize = 16.0;
const double _kSubtitleFontSize = 12.0;
const double _kNotchedSubtitleFontSize = 14.0;

enum _CupertinoListTileType { base, notched }
```

2024-06-23 13:37 UTC, Strafe0 approved these changes

2024-06-23 13:37 UTC, Strafe0 commented on lib/src/core/theme/app_theme.dart
Правильно ли я понял, что ты хотел сделать тему синглтоном? Если да, то можно сделать
```dart
static final AppTheme _singleton = AppTheme._(...);
factory AppTheme() {
   return _singleton;
}
```
В таком случае при вызове `AppTheme()` объект не будет создаваться каждый раз при вызове конструктора.

2024-06-23 13:37 UTC, Strafe0 commented on lib/src/presentation/pages/home_page.dart
> +          children: const [_ListSection()],
Производительнее будет "лениво" создавать список задач с помощью
```dart
SliverList(
   delegate: SliverChildBuilderDelegate(
      // builder
   )
)
```
Иначе при большом количестве задач могут возникнуть лаги интерфейса.

2024-06-23 13:37 UTC, Strafe0 commented on lib/src/presentation/pages/todo_page/description_field.dart
> +class TextField extends StatelessWidget {
Имя класса полностью совпадает с материаловским `TextField`, в какой-то момент может возникуть путаница и конфликты.

2024-06-23 13:37 UTC, Strafe0 commented on lib/src/presentation/pages/todo_page/switches.dart
> +        final dateFormat = DateFormat('d MMMM y', 'ru');
Можно вынести `DateFormat` в отдельное место, наверняка где-то еще пригодится.

2024-06-23 14:41 UTC, vilorg commented on README.md
> +[https://github.com/coma8765/literate-computing-machine/releases/tag/part-01](https://github.com/coma8765/literate-computing-machine/releases/tag/part-01)
Приветик. Хотелось бы Readme файлик сделать более объемным и читаемым. На будущее)

2024-06-23 15:25 UTC, vilorg requested changes
Вот, накидал. Посмотри и исправь)

2024-06-23 15:25 UTC, vilorg commented on analysis_options.yaml
> +    prefer_single_quotes: true  # Uncomment to enable the `prefer_single_quotes` rule
Смотри, тут у меня возникает подозрение, что нельзя так беспорядочно игнорировать линтеровские правила. Я бы посоветовал этого избегать. 
Если ты считаешь, что это не так, объясни)

2024-06-23 15:25 UTC, vilorg commented on assets/design/home-screen-1-dark.jpg
Тут вопрос по ассетам. Косатеся всех. Не понимаю, зачем вообще кидать их в эту папку. Если это превью приложения - их можно разместить в директории Docs, например, как ты это сделал , или же в отдельной ветке.
Вот пример:
https://gist.github.com/chrisryana/b2657506eeb489867f3e47343588343e

2024-06-23 15:25 UTC, vilorg commented on fonts/SFPRODISPLAYREGULAR.OTF
Flutter автоматически добавляет SF шрифты в CupertinoApp, поэтому можно было не заморчиваться)

2024-06-23 15:25 UTC, vilorg commented on ios/Runner/Assets.xcassets/AppIcon.appiconset.old/Contents.json
AppIcon не подгрузились, к сожалению, в ios сборку, но это не страшно)
Можешь использовать flutter_launcher_icons

2024-06-23 15:25 UTC, vilorg commented on l10n.yaml
Смысл было кидать l10n конфигурацию, если она у тебя не используется в приложении?

2024-06-23 15:25 UTC, vilorg commented on lib/main.dart
> +import 'package:todo/src/core/profiling/sentry.dart';
Не стоит игнорировать правила сортировки у линтера. Исправляется в один клик :) 
![image](https://github.com/coma8765/literate-computing-machine/assets/60550560/0cd5c545-22e3-4570-a01f-011ad3244d45)

2024-06-23 15:25 UTC, vilorg commented on lib/main.dart
> +      // home: const UtilsPage(),
Лишние комментарии также лучше подчищать

2024-06-23 15:25 UTC, vilorg commented on lib/src/core/profiling/sentry.dart
Не совсем помнию, зачем вообще этот функционал в TODO приложение? Объясни, пожалуйста!

2024-06-23 15:25 UTC, vilorg commented on lib/src/core/theme/text_theme.dart
> +        height: 24 / 20,
не очень понимаю абривиатуру 24/20. Можно было взять из фигмы размеры

2024-06-23 15:25 UTC, vilorg commented on lib/src/core/theme/theme.dart
всегда лучше использовать не относительный, а абсолютный путь. Производительность будет быстрее)

2024-06-23 15:25 UTC, vilorg commented on lib/src/domain/entities/fake/todo_fake.dart
> +class TODOFactory extends ModelFactory<TODO> {
У dart используется camelCase нейминг. TODO - капсом, звучит как не очень крутой план. 
Вместо этого, можно было бы оставить ToDoFactory)

2024-06-23 15:25 UTC, vilorg commented on lib/src/presentation/pages/home_page.dart
> +const _kPageTitle = 'Мои дела';
> почему все константы снаружи класса
Коллега дело говорит. Лучше это закидывать через тему и т.п. вещи. Тут я посоветовал использовать локализацию

2024-06-23 15:25 UTC, vilorg commented on lib/src/presentation/pages/todo_page/description_field.dart
> +class TextField extends StatelessWidget {
Соглашусь, все так и есть. Это очень может плохо повлиять на доработку приложения!

2024-06-23 15:25 UTC, vilorg commented on lib/src/presentation/pages/todo_page/switches.dart
> +        child: SizedBox(
Зачем вообще использовать лишние виджеты?

2024-06-23 15:25 UTC, vilorg commented on lib/src/presentation/pages/todo_page/switches.dart
Также хочу написать, что я бы разделил абстракцию, от имплементации в разные файлы. Получается слишком большой файл.

2024-06-23 15:25 UTC, vilorg commented on lib/src/presentation/pages/todo_page/todo_page.dart
Опять же, очень большой нечитаемый текст(

2024-06-23 15:25 UTC, vilorg commented on lib/src/presentation/pages/todo_page/todo_page.dart
> +);
Смысл каждый раз в начале файла прописывать константы. Их можно вынести в отдельный файл

2024-06-23 15:25 UTC, vilorg commented on lib/src/presentation/pages/utils_page.dart
> +  Widget _buildActionTile({
Очень фиговая практика виджеты выносить в методы. Лучше использовать классы. Так у тебя один и тот же виджет может переиспользоваться, а не рендериться заново.

2024-06-23 15:25 UTC, vilorg commented on lib/src/presentation/widgets/date_picker/android_date_picker.dart
> +}
А как так с неймингом? Вроде вызываешь android метод, а выходит ios)

2024-06-23 15:25 UTC, vilorg commented on lib/src/presentation/widgets/list_tiles/rounded_checkbox.dart
> +        value: false,
у тебя чекбокс без логики? Зачем?

2024-06-23 15:25 UTC, vilorg commented on lib/src/presentation/widgets/list_tiles/slaidable_list_tile.dart
> +class CustomSlaidableListTile extends CustomListTile {
Очепятка)

2024-06-23 15:25 UTC, vilorg commented on lib/src/presentation/widgets/list_tiles/slaidable_list_tile.dart
> +    return Slidable(
Все таки, есть dismissable, он идет из коробки. 
Также у тебя кропиться части слева и справа. Вот пример:
![image](https://github.com/coma8765/literate-computing-machine/assets/60550560/328b4737-1d45-43bf-b80d-4502c41656d4)

2024-06-23 15:25 UTC, vilorg commented on lib/src/presentation/widgets/list_tiles/slaidable_list_tile.dart
> +            onPressed: (context) {},
А где логика?(

2024-06-23 15:25 UTC, vilorg commented on lib/src/presentation/widgets/multi_toggle_switch/multi_toggle_switch.dart
> +  }
Опять же, мы стараемся избегать методов, переходим на классы - производительность)

2024-06-23 15:25 UTC, vilorg commented on lib/src/presentation/widgets/multi_toggle_switch/multi_toggle_switch.dart
Много букв, сложно читать(

2024-06-23 22:10 UTC, coma8765 commented on README.md
> +[https://github.com/coma8765/literate-computing-machine/releases/tag/part-01](https://github.com/coma8765/literate-computing-machine/releases/tag/part-01)
привет привет, согласен, сделал за 5 минут, так-что качество соответствует

2024-06-23 22:12 UTC, coma8765 commented on analysis_options.yaml
> +    prefer_single_quotes: true  # Uncomment to enable the `prefer_single_quotes` rule
На счёт avoid print, согласен, итс копипаст.
Про prefer_single_quotes, я считаю что в коде должен использоваться один тип кавычек.

2024-06-23 22:16 UTC, coma8765 commented on analysis_options.yaml
> +    prefer_single_quotes: true  # Uncomment to enable the `prefer_single_quotes` rule
Исправлено 4b6ccf5

2024-06-23 22:17 UTC, coma8765 commented on assets/design/home-screen-1-dark.jpg
это для pixel perfect библиотеки, https://pub.dev/packages/pixel_perfect

2024-06-23 22:18 UTC, coma8765 commented on ios/Runner/Assets.xcassets/AppIcon.appiconset.old/Contents.json
очень странно, у меня на эмулятор и на физическом отображается

2024-06-24 08:40 UTC, vilorg commented on analysis_options.yaml
> -    avoid_print: false  # Uncomment to disable the `avoid_print` rule
Молодец. Что по остальным?

2024-06-24 08:53 UTC, coma8765 commented on lib/src/presentation/pages/todo_page/description_field.dart
> +class TextField extends StatelessWidget {
исправлено 743ca82

2024-06-24 08:55 UTC, coma8765 commented on fonts/SFPRODISPLAYREGULAR.OTF
есть опасность, что запустив к примеру с веба он будет скачивать универсальный шрифт размером 10МБ

2024-06-24 08:59 UTC, coma8765 commented on l10n.yaml
исправленно 23048b3

2024-06-24 09:02 UTC, coma8765 commented on lib/src/presentation/widgets/list_tiles/slaidable_list_tile.dart
> +class CustomSlaidableListTile extends CustomListTile {
исправлено b49bc8f

2024-06-24 09:03 UTC, coma8765 commented on lib/src/presentation/widgets/list_tiles/slaidable_list_tile.dart
> +    return Slidable(
у dismissable, как я понимаю, нет поддержки нескольких действий

2024-06-24 09:07 UTC, coma8765 commented on analysis_options.yaml
> -    avoid_print: false  # Uncomment to disable the `avoid_print` rule
окккк, пояснияснений:


```yaml
analyzer:
  errors:
    prefer_int_literals: ignore # чтоб можно было писать 0.0, чтоб не было не было автоматического приведения к даббл
  language:
    strict-casts: true  # чтоб все приведения к типам были описаны в коде, а не происходили магически

  exclude: # игнор файлов из кодогенерагии
    - "**/*.g.dart"
    - "**/*.freezed.dart"
```

2024-06-24 09:07 UTC, coma8765 commented on lib/src/presentation/widgets/multi_toggle_switch/multi_toggle_switch.dart
я считаю, что лучше много букв, но смысл ясен прямо

2024-06-24 09:58 UTC, vilorg commented on fonts/SFPRODISPLAYREGULAR.OTF
Нет, у нас же приложение под ios и android только. Поэтому все норм.

2024-06-24 09:58 UTC, vilorg commented on lib/src/presentation/widgets/list_tiles/slaidable_list_tile.dart
> +    return Slidable(
Нужно всего 2 действия. Удалить и апрувнуть

2024-06-24 09:59 UTC, vilorg commented on lib/src/presentation/widgets/multi_toggle_switch/multi_toggle_switch.dart
Нет, нужно разбивать на слои. Один слой абстракция - второй имплентация. Так лучше читается

2024-06-24 10:00 UTC, vilorg commented on analysis_options.yaml
> -    avoid_print: false  # Uncomment to disable the `avoid_print` rule
Нет. По астальным - в плане по другим замечаниям)

2024-06-24 10:01 UTC, vilorg approved these changes

2024-06-24 10:36 UTC, coma8765 commented on lib/src/presentation/widgets/list_tiles/slaidable_list_tile.dart
> +            onPressed: (context) {},
Исправлено 33b4641

2024-06-24 10:39 UTC, coma8765 commented on lib/src/presentation/widgets/list_tiles/slaidable_list_tile.dart
> +    return Slidable(
<img width="128" alt="Снимок экрана 2024-06-24 в 13 38 52" src="https://github.com/coma8765/literate-computing-machine/assets/68271457/bd4366eb-4c84-4e95-ba6f-bdf16ff065da">

исправлено

2024-06-25 12:04 UTC, coma8765 commented on analysis_options.yaml
> -    avoid_print: false  # Uncomment to disable the `avoid_print` rule
а, в процессе

2024-06-25 12:47 UTC, coma8765 commented on lib/src/core/theme/app_theme.dart
Исправлено 1c92a98

Спасибо большое, [Strafe0](https://github.com/Strafe0), за большое количество полезных исправлений)

2024-06-25 12:48 UTC, coma8765 commented on lib/src/presentation/pages/home_page.dart
> +          children: const [_ListSection()],
Знаешь как внутри секции их лениво создавать?
Т.к. по сути создание списка находится там.

2024-06-25 12:53 UTC, coma8765 commented on lib/src/presentation/widgets/multi_toggle_switch/multi_toggle_switch.dart
> +  }
Исправлено 2e3bf14

2024-06-25 13:07 UTC, coma8765 commented on lib/src/presentation/pages/todo_page/switches.dart
> +        final dateFormat = DateFormat('d MMMM y', 'ru');
Исправлено a0ee941

2024-06-25 17:28 UTC, merged